import { getCallback, getRound, percentageOf } from "./utils.js";

const DEF_OPTS = {round: true}
const cp = Object.assign;
const isCount = (value) => (typeof value === 'number' && value > 0);

/**
 * Calculate compound interest.
 * 
 * Despite offering a lot of flexibility, this function is rather
 * simplistic in its implementation of the interest algorithm.
 * 
 * Without any callbacks, it could work to calculate interest being
 * generated on a fixed starting value that you aren't adding to
 * or subtracting from, which isn't a particularly realistic model
 * for much of anything in a modern financial sense.
 * 
 * For something like interest on a term savings that you make regular
 * contributions to, or a loan which you make regular payments to,
 * you'd need to use the callback options.
 * 
 * @param {number} value - The initial value to apply interest to.
 * @param {(number|GetInterestRate)} rate - The interest rate.
 * 
 * If this is a number, it must be a percentage value;
 * see {@link percentageOf} or {@link getPercent} for details.
 * 
 * If this is a function, it will be called each time interest is being
 * applied, and must return a percentage value number as defined above.
 * 
 * @param {number} times - Number of times to apply interest.
 * @param {object} [opts] Options.
 * 
 * If this is omitted the default is `{round: true}`;
 * See {@link getRound} for more details.
 * 
 * In addition to the getRound() and getPercent() options, there are also
 * a few options specific to this function.
 * 
 * @param {InterestCallback} [opts.preInterest] Called at the start of each
 * iteration, before interest has been calculated.
 * 
 * Say you wanted to make a payment of 100 every term, you could do so via:
 * 
 * ```js
 * {
 *   payment: 100,
 *   preInterest(ctx) {
 *     ctx.info.value -= ctx.opts.payment;
 *   },
 * }
 * ```
 * 
 * @param {InterestCallback} [opts.postInterest] Called at the end of each
 * iteration, after interest has been added and all properties in the
 * state info object have been updated.
 * 
 * @returns {CompoundInterestInfo}
 */
export function compoundInterest(value, rate, times=0, opts = DEF_OPTS) {
  let round = getRound(opts);
  let rates = (typeof rate === 'function') ? [] : null;
  let info = {
    interest: [],
    rates,
    totalInterest: 0,
    value,
    values: [value],
  }

  let pre = getCallback(opts.preInterest);
  let post = getCallback(opts.postInterest);

  for (let t = 0; t < times; t++) {
    let ctx = { info, time: t, opts, round };

    if (rates) {
      ctx.rate = rate.call(ctx, ctx);
      rates.push(ctx.rate);
    }
    else {
      ctx.rate = rate;
    }

    pre.call(ctx, ctx);
    
    let interest = percentageOf(info.value, ctx.rate, round.nestOpts);
    info.interest.push(interest);
    info.value = round(info.value + interest);
    info.values.push(round(info.value));
    info.totalInterest = round(info.totalInterest + interest);

    post.call(ctx, ctx);
  }

  return info;
}

/**
 * A unit of time in which interest is applied.
 * 
 * This is an abstract class and/or interface that isn't used directly.
 * See {@link BaseInterestTerm} and {@link NestingInterestTerm} for the
 * real classes that implement/extend this.
 * 
 * @abstract
 */
export class InterestTerm {
  /**
   * @protected
   * @param {string} name - Name of term.
   * @param {object} opts - Options.
   */
  constructor(name, opts = {}) {
    /** @type {string} */
    this.name = name;
    /** @type {object} */
    this.opts = opts;
  }

  /**
   * Calculate interest info.
   * @param {number} value - Starting value to apply interest to.
   * @param {number} [times=1] Number of times to apply this term.
   * @param {NestingInterestInfo[]} [from] All terms above this one.
   * The _last_ item in the list is the term that called this directly.
   * @returns {(BaseInterestInfo|NestingInterestInfo)}
   */
  get(value, times=1, from=[]) {
    console.error({value, times, from});
    throw new Error("Abstract method 'get' not implemented");
  }

  /**
   * Set (update) the options for this term.
   * @param {object} opts - Options to add/update.
   * 
   * While there is no direct way to unset/delete a method,
   * setting its value to null should accomplish the same thing.
   * 
   * @returns {this}
   */
  set(opts) {
    cp(this.opts, opts);
    return this;
  }
}

/**
 * The base-level term that interest is applied to.
 */
export class BaseInterestTerm extends InterestTerm {
  /**
   * Use InterestBuilder rather than constructing this manually.
   * 
   * @param {string} name - Name of this term.
   * @param {(number|GetInterestRate)} rate - Interest rate to be applied.
   * @param {object} opts - See {@link compoundInterest} for details.
   * 
   * A _copy_ of these options will be generated by the get() method,
   * which will add two additional properties automatically, designed
   * to be used by any custom callback functions supported by the
   * compoundInterest() function.
   * 
   * @param {BaseInterestTerm} [opts.base] `this` instance;
   * is added dynamically, cannot be specified manually!
   * @param {NestingInterestInfo[]} [opts.from] The `from` argument;
   * is added dynamically, cannot be specified manually!
   * 
   */
  constructor(name, rate, opts) {
    super(name, opts);
    this.rate = rate;
  }

  /**
   * @returns {BaseInterestInfo}
   */
  get(value, times=1, from=[]) {
    let { rate } = this;
    let opts = cp({}, this.opts, { base: this, from });
    let info = compoundInterest(value, rate, times, opts);
    info.term = this;
    return info;
  }
}

/**
 * Interest Terms that contain a set number of smaller terms.
 */
export class NestingInterestTerm extends InterestTerm {
  /**
   * Use InterestBuilder rather than constructing this manually.
   *
   * @param {string} name - Name of this term.
   * @param {InterestTerm} nested - The term that is being nested.
   * @param {number} count - Number of times `nested` occurs in this term.
   * 
   * For example, if `nested` is a BaseInterestTerm called `month` and
   * you are creating a NestingInterestTerm called `year`, you would
   * set this to `12` to indicate there are 12 months in a year.
   * 
   * @param {object} [opts] See {@link compoundInterest} for details.
   * 
   * In addition to the options supported by compoundInterest(),
   * and the ones added automatically by the BaseInterestTerm's get()
   * method, there are a few options that can be set specifically
   * on individual NestingInterestTerm instances that will be used
   * by their get() methods.
   * 
   * @param {function} [opts.preTerm] Called at the start of each iteration,
   * before the nested term's get() method is called.
   * @param {function} [opts.postTerm] Called at the end of each iteration,
   * after every other operation has been completed.
   */
  constructor(name, nested, count, opts = {}) {
    super(name, opts);
    this.nested = nested;
    this.count = count;
    if (nested.rate) {
      this.rate = nested.rate * count;
    }
  }

  /**
   * @returns {NestingInterestInfo}
   */
  get(value, times=1, from=[]) {
    let { opts } = this;
    let nc = this.count;
    let pre = getCallback(opts.preTerm);
    let post = getCallback(opts.postTerm);
    let info = {
      term: this,
      totalInterest: 0,
      value,
      with: [],
    }

    from.push(info);

    for (let t = 0; t < times; t++) {
      let ctx = { info, opts, time: t }

      pre.call(ctx, ctx);

      let nextInfo = this.nested.get(info.value, nc, from);
      info.with.push(nextInfo);
      info.value = nextInfo.value;
      info.totalInterest += nextInfo.totalInterest;

      post.call(ctx, ctx);
    }

    return info;
  }
}

/**
 * A factory class for building a complete set of interest terms.
 */
export class InterestBuilder {
  /**
   * Build an InterestBuilder factory instance.
   * @param {object} [opts] Options.
   * 
   * See {@link getRound}, and {@link getPercent} for details on the various
   * options supported here. See {@link compoundInterest} for the defaults.
   * 
   * The result of `getRound(opts).nestOpts` will be assigned to `this.opts`
   * for use by the term() method.
   * 
   * @param {object} [opts.termTemplates] Add or override term templates.
   * 
   * Term templates allow you to create terms by specifying only the name of
   * each term, and allowing the count to be determined based on rules which
   * describe the relationships between specific term units.
   * 
   * The names of the templates must be lowercase!
   * 
   * See {@link TermTemplates} for a list of pre-defined term template names.
   */ 
  constructor(opts = DEF_OPTS) {
    this.opts = getRound(opts).nestOpts;
    this.base = null;
    this.current = null;
    this.templates = cp({}, TermTemplates, opts.termTemplates);
  }

  /**
   * Add a Term.
   * 
   * The first time this is called a BaseInterestTerm will be added.
   * 
   * Each subsequent time a NestingInterestTerm nesting the prior term
   * will be added.
   * 
   * @param {string} name - Name for Term to add.
   * @param {(number|GetInterestRate)} [value=0] The rate or count value.
   * 
   * The first time this method is called the `value` will be used as
   * the `rate` argument for the BaseInterestTerm constructor. 
   * That is the only time this may be a function! You can set this to `0`,
   * or omit it entirely if you plan to use the rate() method.
   * 
   * Every subsequent call the `value` will be used as the `count` argument
   * for the NestingInterestTerm constructor. You _may_ set this to `0` or
   * omit it if the `name` argument and the name of the previously added term
   * are compatible, see {@link TermTemplates} for details on predefined term
   * names and which ones can be used in conjunction with each other to set
   * the value automatically. If no compatible templates were found, then this 
   * **MUST** be a number _greater than 0_, otherwise an error will be thrown.
   * 
   * @param {object} [opts] Options for this specific Term.
   * 
   * A new object that composes this argument with the defaults provided
   * by `this.opts` will be used as the options for the term instance. 
   * 
   * This is the place to set options like `preTerm` and `postTerm` which
   * only apply to NestingInterestTerm instances.
   * 
   * @returns {this}
   * @throws {TypeError} If any of the arguments are not valid.
   */
  term(name, value, opts) {
    if (typeof name !== 'string' || name.trim() === '') {
      throw new TypeError('The name must be a non-empty string');
    }

    opts = cp({}, this.opts, opts);

    if (!this.current) {
      this.current = this.base = new BaseInterestTerm(name, value, opts);
    }
    else {
      let cur = this.current;
      if (!isCount(value)) {
        let tmpl = this.templates;
        let at = name.toLowerCase();
        let ct = cur.name.toLowerCase();
        if (tmpl[at] && isCount(tmpl[at][ct])) {
          value = tmpl[at][ct];
        }
        else {
          throw TypeError('The count value must be a number > 0');
        }
      }
      this.current = new NestingInterestTerm(name, cur, value, opts);
    }

    return this;
  }

  /**
   * Set the interest rate based on the current term.
   * 
   * This is meant for times when the known interest rate is based
   * on a larger unit of time than the one its being applied to.
   * 
   * @param {number} rate - The interest rate to be applied.
   * 
   * It will be divided by the `count` of each NestingInterestTerm,
   * and the final result assigned to the BaseInterestTerm.
   * 
   * @example
   * 
   * // Assign a yearly interest rate of 7.5%, applied monthly.
   * let it = (new InterestBuilder())
   *   .term('month') // rate must be omitted or set to `0`
   *   .term('year')  // count is set to `12` via TermTemplates.year.month
   *   .rate(7.5)
   *   .done()
   * 
   * // The resulting object tree will look like:
   * it = { 
   *   #class: 'NestingInterestTerm'
   *   name: 'year', 
   *   count: 12, 
   *   rate: 7.5, 
   *   nested: {
   *     #class: 'BaseInterestTerm'
   *     name: 'month',
   *     rate: 0.625,
   *   },
   * }
   * 
   */
  rate(rate) {
    if (!this.current) {
      throw new RangeError('Cannot set rate before adding a term');
    }

    let term = this.current;

    while (term) {
      term.rate = rate;
      if (term instanceof NestingInterestTerm) {
        rate /= term.count;
        term = term.nested;
      }
      else {
        break;
      }
    }
    
    return this;
  }

  /**
   * Returns the last term that was added so it can be used.
   * @returns {(BaseInterestTerm|NestingInterestTerm)}
   * @throws {RangeError} If you try to finish without setting a rate.
   * That includes if you don't add any terms at all obviously.
   */
  done() {
    if (!this.base?.rate) {
      throw new RangeError('Cannot be done without setting a rate');
    }
    return this.current;
  }
}

/**
 * Pre-defined Term Templates for the InterestBuilder class.
 * 
 * Any of the templates may be used as the BaseInterestTerm.
 * Adding NestingInterestTerm instances via template is only
 * possible if the previously added term has a template which
 * represents a smaller unit of time.
 * 
 * If you attempt to add a NestingInterestTerm using a template
 * name that either doesn't exist, or represents a unit of time
 * smaller than the previously added term, an error will be thrown.
 */
export const TermTemplates = {
  /** day - no smaller unit is pre-defined */
  day: {},
  /** week - 7 days */
  week: {
    day: 7,
  },
  /** month - 30.417 days, 4.345 weeks */
  month: {
    day: 30.417,
    week: 4.345,
  },
  /** quarter - 91.251 days, 13.035 weeks, 3 months */
  quarter: {
    day: 91.251,
    week: 13.035,
    month: 3,
  },
  /** year - 365 days (no leap years), 52.143 weeks, 12 months, 4 quarters */
  year: {
    day: 365,
    week: 52.143,
    month: 12,
    quarter: 4,
  },
}

/**
 * Build an InterestBuilder instance.
 * @param {object} [opts] See {@link InterestBuilder} constructor.
 * @returns {InterestBuilder}
 */
export const buildInterest = (opts) => new InterestBuilder(opts);

/**
 * Context info for compoundInterest() callbacks.
 * @typedef {object} InterestCallbackContext
 * @prop {CompoundInterestInfo} info - Current state info;
 * updated on every iteration.
 * @prop {object} opts - Options passed to the function.
 * 
 * If the function was called from a {@link BaseInterestTerm} instance, 
 * the opts will have extra metadata properties added automatically.
 * See the BaseInterestTerm constructor for details.
 * 
 * @prop {import("./utils.js").RoundFun} round - see {@link getRound}.
 * @prop {number} time - Current iteration; starts at 0.
 */

/**
 * Context info for NestingInterestTerm callbacks.
 * @typedef {object} NestingCallbackContext
 * @prop {NestingInterestInfo} info - Current state info;
 * updated on every iteration of this Term.
 * @prop {object} opts - Options specific to this Term.
 * 
 * If the InterestBuilder was used to create all instances as is highly
 * recommended, `opts.round` will be a round() function returned by the
 * getRound() function. It can be used for any rounding purposes.
 * 
 * @prop {number} time - Current iteration; starts at 0.
 */

/**
 * A callback function for compoundInterest() options.
 * @callback InterestCallback
 * @this {InterestCallbackContext}
 * @param {InterestCallbackContext}
 * @returns {void}
 */

/**
 * A callback function for NestingInterestTerm options.
 * @callback NestingCallback
 * @this {NestingCallbackContext}
 * @param {NestingCallbackContext}
 * @returns {void}
 */

/**
 * A callback function to get the interest rate dynamically.
 * @callback GetInterestRate
 * @this {InterestCallbackContext}
 * @param {InterestCallbackContext} ctx
 * @returns {number} Interest rate.
 * 
 * The return value will be passed to the {@link percentageOf} function,
 * along with the `opts` passed to {@link compoundInterest},
 * so make sure it is in the correct format. 
 * 
 * By default 7% would be represented by the value `7`, but if `opts.decimal` 
 * is true, then it must be specified as `0.07`. If you are writing a library
 * or app where the options may be specified by external sources, you should
 * use `ctx.opts.decimal` to determine what format to return the value in!
 */

/**
 * @typedef {object} IProps
 * @prop {number} totalInterest - The total amount of interest applied.
 * @prop {number} value - The value after applying all interest charges.
 */

/**
 * @typedef {object} CIProps
 * @prop {number[]} interest - List of interest amounts applied.
 * @prop {?number[]} rates - List of interest rates applied.
 * 
 * This is only used if the `rate` argument was a function.
 * If the rate was a number, this property will be null.
 * 
 * @prop {number[]} values - List of all incremental values.
 * 
 * The list starts with the initial value that was passed,
 * and then will have one value for every time interest was applied.
 * 
 * As this list includes the starting value, it will always be
 * 1 item longer than `interest` (and `rates` if it was used).
 * In order to compare them directly, you can use
 * `values.slice(1)` for a version without the starting value.
 */

/**
 * Compound Interest Info
 * @typedef {IProps & CIProps} CompoundInterestInfo
 */

/**
 * @typedef {object} ITProps
 * @prop {InterestTerm} term - The instance that generated the info.
 */

/**
 * Interest Info for Base Term
 * @typedef {ITProps & CompoundInterestInfo} BaseInterestInfo
 */

/**
 * @typedef {object} NIProps
 * @prop {(BaseInterestInfo | NestingInterestInfo)[]} with
 * The info for each count of a nested term will be added here.
 */

/**
 * Interest Info for Nesting Term
 * @typedef {ITProps & IProps & NIProps} NestingInterestInfo
 */
